### Objective
Train and evaluate a Linear Regression model to predict house prices using the Boston House Prices dataset.

About the dataset:
The Boston House Prices dataset contains housing data with features like crime rate, number of rooms, tax rate, etc., and the target is the median value of owner-occupied homes (in $1000s).


### Task Description
Write a Python program that:
- Loads the Boston House Prices dataset (CSV from https://www.kaggle.com/datasets/vikrishnan/boston-house-prices).
- Splits the data into training and testing sets.
- Trains a Linear Regression model using scikit-learn.

### Evaluates the model using:
- MAE
- MSE
- R² score

Clearly displays and explains the evaluation results in the output.
(Optional) Plot actual vs predicted house prices.
You may use libraries like NumPy, pandas, matplotlib, scikit-learn.

## install kaggle

In [2]:
!pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\moust\anaconda3\lib\site-packages (1.0.2)
Requirement already satisfied: kagglesdk<1.0,>=0.1.22 in c:\users\moust\anaconda3\lib\site-packages (from kagglehub) (0.1.30)
Requirement already satisfied: packaging in c:\users\moust\anaconda3\lib\site-packages (from kagglehub) (24.1)
Requirement already satisfied: pyyaml in c:\users\moust\anaconda3\lib\site-packages (from kagglehub) (6.0.1)
Requirement already satisfied: requests in c:\users\moust\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\moust\anaconda3\lib\site-packages (from kagglehub) (4.66.5)
Requirement already satisfied: protobuf in c:\users\moust\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.22->kagglehub) (5.29.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\moust\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\moust\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\moust\anaconda3\lib\site-packages (from requests->kagglehub) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\moust\anaconda3\lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in c:\users\moust\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)

## import libraries

In [122]:
import kagglehub
import pandas as pd
import os
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

## download data

In [16]:
# Download latest version
path = kagglehub.dataset_download("vikrishnan/boston-house-prices")

print("Path to dataset files:", path)

Path to dataset files: C:\Users\moust\.cache\kagglehub\datasets\vikrishnan\boston-house-prices\versions\1

In [28]:
print(os.listdir(path))

['housing.csv']

In [44]:
data = pd.read_csv(path+ '/housing.csv', sep=r"\s+", header=None)

## data descibe

In [46]:
data.head(5)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

In [48]:
data.shape

(506, 14)

In [50]:
columns = [
    "CRIM", "ZN", "INDUS", "CHAS", "NOX", "RM",
    "AGE", "DIS", "RAD", "TAX", "PTRATIO", "B",
    "LSTAT", "MEDV"
]

data.columns = columns

In [52]:
data.head(5)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0,0.538,6.575,65.2,4.0900,1,296.0,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0,0.469,6.421,78.9,4.9671,2,242.0,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0,0.469,7.185,61.1,4.9671,2,242.0,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0,0.458,6.998,45.8,6.0622,3,222.0,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0,0.458,7.147,54.2,6.0622,3,222.0,18.7,396.90,5.33,36.2

## splitting data

In [104]:
x=data.drop('MEDV',axis=1)
y=data.MEDV

In [114]:
xtrain,xtest,ytrain,ytest = train_test_split(x,y,train_size=0.8,random_state=42)

In [116]:
lr= LinearRegression()

In [118]:
print(type(lr))

<class 'sklearn.linear_model._base.LinearRegression'>

In [120]:
lr.fit(xtrain,ytrain)

LinearRegression()

## measure accuracy

In [134]:
lr.score(xtrain,ytrain)

0.7508856358979673

In [136]:
lr.score(xtest,ytest)

0.6687594935356329

In [146]:
mean_absolute_error(ytest,lr.predict(xtest))

3.189091965887843

In [148]:
mean_squared_error(ytest,lr.predict(xtest))

24.29111947497345

In [150]:
r2_score(ytest,lr.predict(xtest))

0.6687594935356329