# Objective
Implement Gradient Descent in Python for a problem with more than one variable.

# Task Description
Write a Python program that applies gradient descent to a multivariable linear regression problem.
Your code should:
- Use a dataset with at least two features
- Initialize model parameters (weights)
- Apply gradient descent to update the parameters
- Print the final values of the parameters
Note: You may use NumPy, but do not use ready-made ML libraries (e.g., scikit-learn).

## import libraries

In [8]:
import numpy as np
import pandas as pd

## creating data

This dataset represents cars with different weights, engine sizes and fuel consumption.

In [20]:
data = pd.DataFrame({
    "weight": [
        950,1000,1050,1100,1150,1200,1250,1300,1350,1400,
        1450,1500,1550,1600,1650,1700,1750,1800,1850,1900
    ],
    "engine_size": [
        1.0,1.1,1.2,1.3,1.4,1.4,1.5,1.6,1.6,1.7,
        1.8,1.8,1.9,2.0,2.0,2.1,2.2,2.3,2.4,2.5
    ],
    "fuel_consumption": [
        4.9,5.1,5.3,5.6,5.8,6.0,6.2,6.5,6.7,7.0,
        7.2,7.4,7.7,8.0,8.2,8.5,8.8,9.1,9.4,9.8
    ]
})

## data description

In [22]:
data.head(5)

   weight  engine_size  fuel_consumption
0     950          1.0               4.9
1    1000          1.1               5.1
2    1050          1.2               5.3
3    1100          1.3               5.6
4    1150          1.4               5.8

In [24]:
data.shape

(20, 3)

In [27]:
data.describe()

            weight  engine_size  fuel_consumption
count    20.000000    20.000000         20.000000
mean   1425.000000     1.740000          7.160000
std     295.803989     0.435769          1.493988
min     950.000000     1.000000          4.900000
25%    1187.500000     1.400000          5.950000
50%    1425.000000     1.750000          7.100000
75%    1662.500000     2.025000          8.275000
max    1900.000000     2.500000          9.800000

In [31]:
data.dtypes

weight                int64
engine_size         float64
fuel_consumption    float64
dtype: object

## data preparation

In [36]:
x=data.drop('fuel_consumption',axis=1)
y=data.fuel_consumption

In [38]:
x.head(2)

   weight  engine_size
0     950          1.0
1    1000          1.1

## Implement Gradient Descent
y_predict=m1*weight+m2*engine_size+b

In [82]:
m1=0.1
m2=0.7
b=0.5
iterations=10000
lrate=0.01
x1=data['weight'].values
x2=data['engine_size'].values
m=len(y)
x1 = (x1 - x1.mean()) / x1.std()
x2 = (x2 - x2.mean()) / x2.std()

lrate = 0.001

In [84]:
for i in range(iterations):

    y_pred = m1 * x1 + m2 * x2 + b

    error = y_pred - y

    cost = (1/(2*m)) * np.sum(error**2)

    dm1 = (1/m) * np.sum(error * x1)
    dm2 = (1/m) * np.sum(error * x2)
    db  = (1/m) * np.sum(error)

    m1 = m1 - lrate * dm1
    m2 = m2 - lrate * dm2
    b  = b  - lrate * db

    if i % 1000 == 0:
        print("Iteration:", i, "Cost:", cost)

Iteration: 0 Cost: 22.396201456332467
Iteration: 1000 Cost: 3.006514213765085
Iteration: 2000 Cost: 0.4095931571115258
Iteration: 3000 Cost: 0.05893511090501794
Iteration: 4000 Cost: 0.01152843102255628
Iteration: 5000 Cost: 0.005113211107413154
Iteration: 6000 Cost: 0.004239928360425876
Iteration: 7000 Cost: 0.004115956598008062
Iteration: 8000 Cost: 0.00409333549008756
Iteration: 9000 Cost: 0.004084460571372728